php:
    image: php:7.3-apache
    ports:
        - "80:80"
    volumes:
        - ./php:/var/www/html

db:
    image: mysql:5.7.18
    volumes:
        - .db_data:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: php-mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: admin1234